---
- name: Install necessary packages
  import_tasks: install_packages.yml

- name: Disk and partition encryption
  import_tasks: encryption.yml

- name: Apply network settings
  import_tasks: network_settings.yml

- name: Apply CPU settings
  import_tasks: cpu_settings.yml
