---
# Default values for role variables
# Used when no specific values are provided in inventory

disk_to_encrypt: false  # Default disk to encrypt (empty by default)
partition_to_encrypt: false  # Default partition to encrypt (empty by default)

encrypt_pass: "example_pass"